version: '3'
services:
    #app-php:
    # тут только Dockerfile php + symfony run server

    wiki-app:
        restart: unless-stopped
        build:
            dockerfile: ../Dockerfile
            context: ./docker
        ports:
            - 56788:80