version: '3'
services:
    #app-php:
    # тут только Dockerfile php + symfony run server

    wiki-app:
#        volumes:
#            - ../:/var/www/app
        restart: unless-stopped
        #command: sleep 3000
        build:
            dockerfile: centos.dockerfile
            context: ./
        ports:
            - 74:8000
            - 73:8001
