version: '3'
services:
    #app-php:
    # тут только Dockerfile php + symfony run server

    wiki-app:
        restart: unless-stopped
        command: sleep 3000
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 56788:8000