version: '3'
services:
    #app-php:
    # тут только Dockerfile php + symfony run server

    app-search:
        restart: unless-stopped
        image: getmeili/meilisearch
#        volumes:
#            - ./volumes/meilisearch:/data.ms
        expose:
            - 7700
        ports:
            - 56789:7700